-- MySQL Script generated by MySQL Workbench
-- Fri Mar 12 00:27:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id_rol` INT(1) NOT NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_user` INT(2) NOT NULL,
  `usuario` VARCHAR(100) NULL,
  `password` VARCHAR(240) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `estado` TINYINT NOT NULL,
  `id_rol(1)` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  INDEX `fk_usuarios_roles_idx` (`id_rol(1)` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`id_rol(1)`)
    REFERENCES `mydb`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`versiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`versiones` (
  `id_version` INT(3) NOT NULL,
  `version` VARCHAR(45) NULL,
  PRIMARY KEY (`id_version`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especialidades` (
  `id_especialidad` INT(4) NOT NULL,
  `especialidad` VARCHAR(255) NULL,
  `id_version` INT(3) NOT NULL,
  PRIMARY KEY (`id_especialidad`),
  INDEX `fk_especialidades_versiones1_idx` (`id_version` ASC) VISIBLE,
  CONSTRAINT `fk_especialidades_versiones1`
    FOREIGN KEY (`id_version`)
    REFERENCES `mydb`.`versiones` (`id_version`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id_categoria` INT(4) NOT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  `portadascol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo` (
  `id_tipo` INT(3) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`archivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`archivos` (
  `id_archivo` INT NOT NULL AUTO_INCREMENT,
  `titulo` TEXT(500) NOT NULL,
  `ruta` VARCHAR(255) NOT NULL,
  `autor` VARCHAR(150) NULL,
  `tutor` VARCHAR(150) NULL,
  `fecha_publicacion` DATE NULL,
  `uuid` VARCHAR(40) NOT NULL,
  `resumen` TEXT NULL,
  `id_categoria` INT NULL,
  `portada` VARCHAR(100) NOT NULL,
  `id_especialidad` INT(4) NOT NULL,
  `d_categoria` INT(4) NOT NULL,
  `id_tipo` INT(3) NOT NULL,
  PRIMARY KEY (`id_archivo`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `portada_UNIQUE` (`portada` ASC) VISIBLE,
  INDEX `fk_archivos_especialidades1_idx` (`id_especialidad` ASC) VISIBLE,
  INDEX `fk_archivos_categorias1_idx` (`d_categoria` ASC) VISIBLE,
  INDEX `fk_archivos_tipo1_idx` (`id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_archivos_especialidades1`
    FOREIGN KEY (`id_especialidad`)
    REFERENCES `mydb`.`especialidades` (`id_especialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivos_categorias1`
    FOREIGN KEY (`d_categoria`)
    REFERENCES `mydb`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivos_tipo1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `mydb`.`tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
